apiVersion: v1
kind: ConfigMap
metadata:
  name: airbnb-config
  namespace: airbnb-clone
data:
  # API Configuration
  PORT: "4000"
  JWT_EXPIRY: "20d"
  COOKIE_TIME: "7"
  COOKIE_SECURE: "false"        # set to "true" when served over HTTPS
  COOKIE_SAMESITE: "lax"        # use "none" when secure cookies over HTTPS
  ALLOWED_ORIGINS: "http://4.220.43.120,http://localhost:5173"
  
  # URLs (will be updated after deployment)
  CLIENT_URL: "http://4.220.43.120"
  API_URL: "http://4.220.26.90:4000"
