apiVersion: v1
kind: Secret
metadata:
  name: airbnb-secrets
  namespace: airbnb-clone
type: Opaque
stringData:
  # Database connection (will be updated with actual Cosmos DB connection string)
  DB_URL: "mongodb://airbnb-clone-cosmos:oIJ7DrfndteUPl8H0VAbqCG8jlxV2FLAlESc5So2iRSZXKEoB9KTyItwOtSy5hj1BR4Se8bqsVJPACDb3cVyVQ==@airbnb-clone-cosmos.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@airbnb-clone-cosmos@"
  
  # JWT Configuration
  JWT_SECRET: "8d0045dd1189f0569770d5fb9019d76c979f7e6f29650a5a76990d7f603934d8a12de140467132c4398ecc2ed77e03c5ee53a8469902821c642aa429c6508a64"
  
  # Session Secret
  SESSION_SECRET: "0b2c720f05ef6137db23808975ba4c3db8a94bd381b3484224eca8aa08f687ec1f11639708084abdd061d85cd60a9296af0b5e4361b24a4e8135345a69359ccf"
  
  # Cloudinary Configuration
  CLOUDINARY_NAME: "dbbxzhomi"
  CLOUDINARY_API_KEY: "723641648556277"
  CLOUDINARY_API_SECRET: "x6A1XgZ2T5w_jFoiZa4c4jNBJD4"
